# Generated by Django 3.2.16 on 2023-10-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_userprofile_followed_communities'),
        ('gcleaderboard', '0002_gc_hostel_points_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gc_hostel_points',
            name='participants',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
    ]
