# Generated by Django 3.2.16 on 2023-10-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0004_messcalevent'),
        ('gcleaderboard', '0003_alter_gc_hostel_points_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='gc',
            name='participating_hostels',
            field=models.ManyToManyField(to='messmenu.Hostel'),
        ),
    ]
