# Generated by Django 3.2.16 on 2023-10-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0023_body_canonical_name'),
        ('gcleaderboard', '0004_gc_participating_hostels'),
    ]

    operations = [
        migrations.AddField(
            model_name='gc',
            name='body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gc_body', to='bodies.body'),
            preserve_default=False,
        ),
    ]
