# Generated by Django 3.2.16 on 2023-10-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcleaderboard', '0005_gc_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gc_hostel_points',
            name='participants',
        ),
    ]
