# Generated by Django 3.2.16 on 2023-10-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0023_body_canonical_name'),
        ('gcleaderboard', '0007_alter_gc_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gc',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc_body', to='bodies.body'),
        ),
    ]
